name: flutter_thrivexcode_home_widget
description: "Home widget implementation."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  drift: ^2.28.2
  drift_flutter: ^0.2.7
  sqlite3_flutter_libs: ^0.5.40
  flutter_riverpod: ^2.6.1
  uuid: ^4.5.1
  provider: ^6.1.2
  phosphor_flutter: ^2.1.0
  shared_preferences: ^2.5.3
  flutter_svg: ^2.2.0
  home_widget: ^0.7.0
  go_router: ^16.1.0
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  drift_dev: ^2.28.0
  flutter_gen_runner: ^5.11.0

flutter_gen:
  output: lib/core/assets
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
